name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    steps:
      - uses: google-github-actions/release-please-action@v2
      id: release
      with:
        package-name: conventional-test
        release-type: node
        changelog-types: >
          [{"type":"feat","section":"Features","hidden":false},
          {"type":"fix","section":"Bug Fixes","hidden":false},
          {"type":"docs","section":"Documentation","hidden":false},
          {"type":"deps","section":"dependencies","hidden":false},
          {"type":"chore","hidden":true}]
